### ISSUE TITLE
readInt____ getting incorrect values.

### ISSUE THREAD

**Issue by spAnser** [JoshGlazebrook/smart-buffer#11]
`readInt____` should be returning signed values not unsigned values. The U in `readUInt____` is for `Unsigned`

**Comment by JoshGlazebrook** [comment]
Yikes. This has been fixed in https://github.com/JoshGlazebrook/smart-buffer/commit/603d6ebe20a9b795142323f5e987f6e99cc70d24. Looks like it was from the re-factor in Typescript.

**Comment by spAnser** [comment]
Thanks for the quick fix.

**Comment by JoshGlazebrook** [comment]
Let me know if you find anything else. (Hopefully not)

**Comment by spAnser** [comment]
Well you have a `.remaining()` is there an opposite function that returns the current position?

Was just a though when I was testing some things.

**Comment by JoshGlazebrook** [comment]
If you're using JavaScript you could access the internal resdOffset and writeOffset variables. Otherwise you could do length - remaining()
