### ISSUE TITLE
mark for smart-buffer v4 

### ISSUE THREAD

**Issue by LinBoLen** [JoshGlazebrook/smart-buffer#14]
> Going forward for version 4 (since these will be major breaking changes), I'm looking at adding:
>
> Changing .writeXXX(value, offset) to overwrite in place instead of inserting values. If an offset is  not given, then it will just write at the currently tracked write offset position.
> Adding .insertXXX(value, offset) to function how .writeXXX(value, offset) currently does.
> Adding import { Buffer }...
> Allow more manipulation of the internally tracked automatic read/write buffers.

ref: https://github.com/JoshGlazebrook/smart-buffer/pull/13

**Comment by xsilen** [comment]
any schedule on this?

**Comment by JoshGlazebrook** [comment]
That's a good question, I'll try and work on it later this week if possible. I just started a new job so I've been pretty busy and haven't had a lot of free time (or motivation). But it doesn't seem too much hassle to add these things.

**Comment by JoshGlazebrook** [comment]
I'll be starting on v4 this week.

**Comment by JoshGlazebrook** [comment]
I'd say I'm about 75% done with v4, I should have a test version available hopefully by the end of the weekend.

**Comment by JoshGlazebrook** [comment]
@xsilen @rebrec I have v4 currently on a separate branch in case you want to try out what I have so far locally.

https://github.com/JoshGlazebrook/smart-buffer/tree/v4

**Comment by JoshGlazebrook** [comment]
So since v4 is such a large breaking change already, I'm just going to take the change to trim a lot of legacy stuff like the old constructor patterns, and also get rid of parameters that can be a or b and favor objects instead.

Example:

Current:
```javascript
buff.writeStringNT('hello', 5);
buff.writeStringNT('hello', 'ascii');
buff.writeStringNT('hello', 5, 'ascii');
```

Planned:
```javascript
buff.writeStringNT('hello', {
  offset: 5
};

buff.writeStringNT('hello', {
  encoding: 'ascii'
};

buff.writeStringNT('hello', {
  offset: 5,
  encoding: 'ascii'
};

````

**Comment by xsilen** [comment]
i'm in favor of using object

**Comment by JoshGlazebrook** [comment]
I published a v4 beta to npm if you want to try it out:

```
npm install smart-buffer@4.0.0-beta.1
```

**Comment by JoshGlazebrook** [comment]
V4 has landed.
