### ISSUE TITLE
Int64 support.

### ISSUE THREAD

**Issue by Cyuubi** [JoshGlazebrook/smart-buffer#22]

**Comment by JoshGlazebrook** [comment]
JS/node doesn't support native 64-bit integers.

**Comment by azz** [comment]
Have you seen [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)? (Supported in Node since [10.8.0](https://node.green/#ESNEXT-candidate--stage-3--BigInt))

**Comment by rluvaton** [comment]
I've looked at the code and it seems to be supported...

The docs are outdated
