### ISSUE TITLE
ReadStringNT does not work correctly

### ISSUE THREAD

**Issue by bqio** [JoshGlazebrook/smart-buffer#29]
![Screenshot_4](https://user-images.githubusercontent.com/45086516/82655765-c0322b80-9c33-11ea-862a-21d50356e1b9.png)
![Screenshot_6](https://user-images.githubusercontent.com/45086516/82655922-f1126080-9c33-11ea-9ca7-c5e2a6bafdad.png)

**Comment by JoshGlazebrook** [comment]
This seems to be working just fine. 

```javascript
const buff = SmartBuffer.fromBuffer(Buffer.from('testing\x0ahellothere\0testingsfsdkfdsfldskf'));
const data = buff.readStringNT();

console.log(Buffer.from(data));
console.log(data);
```

It may look like that because 0x0A is the LF (line feed) so whatever is displaying it is handling it as a new line, you can see this in the terminal output below, but the data is still all one string.

```
joshglazebrook-mbp:testing joshglazebrook$ node index
<Buffer 74 65 73 74 69 6e 67 0a 68 65 6c 6c 6f 74 68 65 72 65>
testing
hellothere
```
