### ISSUE TITLE
1.x release uses ES6 const/let causing breakage

### ISSUE THREAD

**Issue by nullfox** [JoshGlazebrook/smart-buffer#9]
It looks in the last batch of releases to NPM on the 1.x major release ES6/Typescript code was pushed into the 1.1.x causing dependencies and sub-dependencies that rely on pre-ES6 code to break.

Can you possibly remove the releases in the 1.x major release from NPM that use ES6/Typescript?

**Comment by JoshGlazebrook** [comment]
Working on that... unpublish seems to be hanging for me.

**Comment by JoshGlazebrook** [comment]
@nullfox Unpublish isn't working at the moment. I went ahead and just published another version (1.1.15), which really is just 1.0.13. So hopefully that fixes it for now.

**Comment by nullfox** [comment]
Cheers, looks like I'm unblocked - thank you!

**Comment by JoshGlazebrook** [comment]
Let me know if you run into any other issues! :-)
